# Name of your workflow
name: My Test Workflow

# Define the trigger event(s)
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:

    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - name: Say hello
            run: echo "Hello, GitHub Actions!"

    # Second job done sequentially, after `say-hello` job
    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
        
            # Use github.com/actions/checkout to check out this repo
          - name: Check out this repo
            uses: actions/checkout@v3
            
            # See where we are in the VM
          - name: Check current directory
            run: pwd
          
          - name: Build STM32CubeIde project
            uses: xanderhendriks/action-build-stm32cubeide@v10.0
            with:
              project-path: ${GITHUB_WORKSPACE}
              project-target: ${GITHUB_WORKSPACE}
            
